# Generated by Django 5.1.5 on 2025-01-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=300)),
                ('Propic', models.ImageField(upload_to='images/')),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
