# Generated by Django 5.1.5 on 2025-01-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sparereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparename', models.CharField(max_length=30)),
                ('spareprice', models.IntegerField()),
                ('sparerpic', models.ImageField(upload_to='images/')),
                ('sparesize', models.CharField(max_length=200)),
                ('sparedesc', models.CharField(max_length=200)),
                ('sparecategory', models.CharField(max_length=20)),
                ('sparemodel', models.IntegerField()),
            ],
        ),
    ]
