# Generated by Django 5.1.5 on 2025-01-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0002_sparereg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparereg',
            old_name='sparerpic',
            new_name='sparepic',
        ),
    ]
