# Generated by Django 5.1.5 on 2025-01-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0004_rename_sparesize_sparereg_sparecolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparereg',
            name='sparemodel',
            field=models.CharField(max_length=30),
        ),
    ]
