# Generated by Django 5.1.5 on 2025-01-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0006_addtocart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparereg',
            old_name='sparecolor',
            new_name='sparecompany',
        ),
    ]
