# Generated by Django 5.1.5 on 2025-02-03 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0008_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressline1', models.CharField(max_length=200)),
                ('addressline2', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_number', models.IntegerField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareapp.newregistration')),
            ],
        ),
    ]
