# Generated by Django 5.1.5 on 2025-02-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0010_order_oderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
    ]
