# Generated by Django 5.0.4 on 2025-02-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0013_billing_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
