# Generated by Django 5.0.4 on 2025-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0014_contact_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparereg',
            name='sparedesc',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='sparereg',
            name='sparemodel',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sparereg',
            name='sparename',
            field=models.CharField(max_length=100),
        ),
    ]
